"""priofile_atatus column of StaffModel modefied

Revision ID: 647cc27ddfce
Revises: 946cbce1073b
Create Date: 2026-06-28 00:04:39.521736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647cc27ddfce'
down_revision = '946cbce1073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('Profile_status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', 'BLACKLISTED', name='staffstatus'), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('Profile_verification_status')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('Profile_verification_status', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=11), nullable=False))
        batch_op.drop_column('Profile_status')
        batch_op.drop_column('staff_bio')

    # ### end Alembic commands ###
