"""switch relationships to backref

Revision ID: 946cbce1073b
Revises: 
Create Date: 2026-06-25 15:56:40.101262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946cbce1073b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Profile_verification_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_column('Profile_verification_status')

    # ### end Alembic commands ###
