"""Flask-Migrate schema synced with User, Staff, Trek, and Booking models and unused bookingModel dropped

Revision ID: ce54aeed5cf4
Revises: 647cc27ddfce
Create Date: 2026-07-10 20:18:12.798725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce54aeed5cf4'
down_revision = '647cc27ddfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_cancel_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_cancel_reason', sa.VARCHAR(length=500), nullable=True))

    op.create_table('reviews',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('trek_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['trek_id'], ['treks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
